### PR TITLE
Webpack Fixes

### PR DESCRIPTION
**Pull request by bradgignac**

### CODE REVIEW

**Comment by bradgignac** [comment]
@eddywashere It appears these image references were copy pasta'd into the repo. It uses Compass' `image-url` helper so they obviously don't work in this repo.

**Comment by eddywashere** [comment]
:shipit:

**Comment by bighappyface** [comment]
+1

@bradgignac would you just close #65 when this is merged?

**Comment by bradgignac** [comment]
@bighappyface Glad you mentioned this. Totally forgot about it.

**Pull request merged**
